services:
  # Base de Datos para Usuarios
  db-users:
    image: postgres:15
    container_name: postgres_users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "root123*"
      POSTGRES_DB: user_db
    ports:
      - "5433:5432" # Puerto diferente para acceso local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_db"]
      interval: 5s
      retries: 5
    volumes:
      - users_data:/var/lib/postgresql/data

  # Base de Datos para Items
  db-items:
    image: postgres:15
    container_name: postgres_items
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "root123*"
      POSTGRES_DB: item_db
    ports:
      - "5434:5432" # Puerto diferente para acceso local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d item_db"]
      interval: 5s
      retries: 5
    volumes:
      - items_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db-users
      - db-items

  user-service:
    build: 
      context: ./microservices/user_infrastructure
      dockerfile: Dockerfile
    container_name: user_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db-users;Port=5432;Database=user_db;Username=postgres;Password=root123*
    ports:
      - "5001:8080"
    depends_on:
      db-users:
        condition: service_healthy

  item-service:
    build: 
      context: ./microservices/item_infrastructure
      dockerfile: Dockerfile
    container_name: item_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db-items;Port=5432;Database=item_db;Username=postgres;Password=root123*
    ports:
      - "5002:8080"
    depends_on:
      db-items:
        condition: service_healthy

  api-gateway:
    build:
      context: ./microservices/gateway_infrastructure
      dockerfile: Dockerfile
    container_name: api_gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__items_cluster__Destinations__destination1__Address=http://item_api:8080
      - ReverseProxy__Clusters__users_cluster__Destinations__destination1__Address=http://user_api:8080
    ports:
      - "5000:8080"
    depends_on:
      - user-service
      - item-service

  angular-web:
    build:
      context: ./angular_frontend
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:80"
    depends_on:
      - api-gateway

volumes:
  users_data:
  items_data: