services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "root123*"
      POSTGRES_DB: task_management_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_management_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  user-service:
    build: 
      context: ./microservices/user_infrastructure
      dockerfile: Dockerfile
    container_name: user_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # IMPORTANTE: Host=db porque es el nombre del servicio arriba
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=task_management_db;Username=postgres;Password=root123*
    ports:
      - "5001:8080"
    depends_on:
      db:
        condition: service_healthy

  item-service:
    build: 
      context: ./microservices/item_infrastructure
      dockerfile: Dockerfile
    container_name: item_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=task_management_db;Username=postgres;Password=root123*
    ports:
      - "5002:8080"
    depends_on:
      db:
        condition: service_healthy

  api-gateway:
    build:
      context: ./microservices/gateway_infrastructure
      dockerfile: Dockerfile
    container_name: api_gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ReverseProxy__Clusters__items_cluster__Destinations__destination1__Address=http://item_api:8080
      - ReverseProxy__Clusters__users_cluster__Destinations__destination1__Address=http://user_api:8080
    ports:
      - "5000:8080"
    depends_on:
      - user-service
      - item-service

  angular-web:
    build:
      context: ./angular_frontend
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:80"
    depends_on:
      - api-gateway

volumes:
  postgres_data: